title: Happy Paws Dog Grooming
description: Professional and caring dog grooming services.
baseurl: "/testing_pages" # the subpath of your site, e.g. /blog
url: "https://mlwyatt.github.io" # replace with your GitHub username
theme: minima
author:
  name: Your Name
  email: your-email@example.com

# Enable Google Analytics or social links if needed later

# Add this to the config file to link the custom CSS
head:
  - "<link rel='stylesheet' href='/assets/css/custom.css' type='text/css' />"
